### ISSUE TITLE
wifi.printpsk() is wrong

### ISSUE THREAD

**Issue by Sequential-circuits** [prajwalkedari/wifimangement_linux#3]
It is wifi.print_psk()

**Comment by prajwalkedari** [comment]
First Thing This only For Linux ![](https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black)
This is Because Linux **Permission File System**
_Try this 2 Method =>_

1. ###  SUDO

>**open Terminal and Type**
    `sudo pip3 install wifimangement_linux `
  `sudo python3 ` 

2. ### Change Permission of file
Basically There are Some file _*.nmconnection_ which contain info network like **wifiname** and respective **password**_(save Password)_
But **Problem** are there permission set on _Root_

>**open Terminal and Type**
`cd /etc/NetworkManager/system-connections/ && sudo chmod 644 *`

**Thank For Using wifimangement_linux Module**
@Sequential-circuits 

Regard
@prajwalkedari  ( _**Author & Developer**_ )
